# Generated by Django 3.2.3 on 2021-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
