# Generated by Django 3.2.3 on 2021-08-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_alter_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
